# Generated by Django 3.2.18 on 2023-10-15 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0006_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile_pic',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='instagram.profile_pic'),
        ),
    ]
